version: '3.9'

services:
    db:
        image: postgres:17-alpine
        ports:
            - "5555:5432"
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=wallet_db

volumes:
    data: